name: Build

on:
  push:

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: sudo apt-get update; sudo apt-get install -y libspeechd-dev
        if: ${{ runner.os == 'Linux' }}
      - run: |
          choco install -qy llvm
          echo LIBCLANG_PATH=c:\program` files\llvm\bin >> $Env:GITHUB_ENV
        if: ${{ runner.os == 'Windows' }}
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt, clippy
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features --examples
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build_linux:
    name: Build Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev
          cargo build --release

  build_linux_32:
    name: Build Linux (32 bits)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y libspeechd-dev:i386 gcc-multilib
          rustup target add i686-unknown-linux-gnu
          cargo build --release --target i686-unknown-linux-gnu

  build_windows:
    name: Build Windows
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: c:\program files\llvm\bin
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          choco install -qy llvm
          cargo build --release

  build_windows_32:
    name: Build Windows (32 bits)
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: c:\program files\llvm\bin
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          choco install -qy llvm
          rustup target add i686-pc-windows-msvc
          cargo build --release --target i686-pc-windows-msvc

  build_uwp:
    name: Build UWP
    runs-on: windows-latest
    env:
      LIBCLANG_PATH: c:\program files\llvm\bin
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          choco install -y llvm
          cargo build --release

  build_macos:
    name: Build MacOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          cargo build --release

  build_android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - run: |
          ./gradlew assemble

  build_ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - run: |
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install cargo-lipo
          cargo lipo --release
